=== makelly/groucho/scripts/publishscript.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Publish script schema",
  "description": "A script schema used by Groucho",
  "type": "object",

  "properties": {

    "title": {
      "description": "The name of the script",
      "type": "string"
    },

    "description": {
      "description": "Short description of the script",
      "type": "string"
    },

    "version": {
      "description": "Script version",
      "type": "string"
    },

    "publisher": {
      "description": "The publisher data file",
      "type": "string"
    },

    "data": {
      "description": "The publisher data file",
      "type": "array",
      "items": {
        "type": "object",

        "properties": {

          "name": {
            "description": "Name of the list of data files",
            "type": "string"
          },

          "list" : {
            "description": "The list of data files",
            "type": "array",
            "items": {
              "type": "string"
            },
            "minItems": 1,
            "uniqueItems": true
          },
          "required": ["name", "list"]

        }
      },
      "minItems": 1,
      "uniqueItems": true
    },

    "events": {
      "description": "Events to publish for the encounter",
      "type": "array",
      "items": {
        "type": "object",

        "properties": {

          "template": {
            "description": "Name of the event template",
            "type": "string"
          },

          "type": {
            "description": "Template format, xml or json",
            "type": "string",
            "enum": ["xml", "json"]
          },

          "eventData": {
            "description": "List contaning the event data files",
            "type": "string"
          }

        },
        "required": ["template", "type", "eventData"]

      },
      "minItems": 1
    },

    "PUBLISH": {
      "description": "The publishing control statements",
      "type": "object",

      "properties": {

        "FOR_EACH_PATIENT": {
          "description": "List containing the patient data",
          "type": "string"
        },

        "FOR_EACH_PROVIDER": {
          "description": "List containing the provider data",
          "type": "string"
        },

        "FOR_EACH_ENCOUNTER": {
          "description": "List containing the encounter data",
          "type": "string"
        }
      },
      "required": ["FOR_EACH_PATIENT", "FOR_EACH_PROVIDER", "FOR_EACH_ENCOUNTER"]
    }
  },
  "required": ["publisher", "data", "events", "PUBLISH"]
}

=== makelly/groucho/scripts/bad7.publish.json
{
  "title": "Bad publish script",
  "description": "Fne not found in data",
  "version": "03/08/2018",
  "publisher": "test.publisher.data.json",

  "data": [
    {"name": "providers", "list": ["test.provider.data.json"]},
    {"name": "encounters", "list": ["test.encounter.data.json"]},
    {"name": "patients", "list": ["test.smith.data.json", "garbage", "test.crowther.data.json"]},
    {"name": "immunizations", "list": ["test.immunization01.data.json", "test.immunization02.data.json"]},
    {"name": "medications", "list": ["test.medication01.data.json", "test.medication02.data.json"]}
  ],

  "events": [
    {"template": "immunization.template.json", "type": "json", "eventData": "immunizations"},
    {"template": "medication.template.xml", "type": "xml", "eventData": "medications"}
  ],

  "PUBLISH": {
    "FOR_EACH_PATIENT": "patients",
    "FOR_EACH_PROVIDER": "providers",
    "FOR_EACH_ENCOUNTER": "encounters"
  }
}

=== makelly/groucho/scripts/bad6.publish.json
{
  "title": "Bad publish script",
  "description": "Undefined name reference in FOR_EACH_ENCOUNTER",
  "version": "03/08/2018",
  "publisher": "test.publisher.data.json",

  "data": [
    {"name": "providers", "list": ["test.provider.data.json"]},
    {"name": "encounters", "list": ["test.encounter.data.json"]},
    {"name": "patients", "list": ["test.smith.patient.data.json", "test.frederikson.patient.data.json", "test.crowther.patient.data.json"]},
    {"name": "immunizations", "list": ["test.immunization01.event.data.json", "test.immunization02.event.data.json"]},
    {"name": "medications", "list": ["test.medication01.event.data.json", "test.medication02.event.data.json"]}
  ],

  "events": [
    {"template": "immunization.beta.template.json", "type": "json", "eventData": "immunizations"},
    {"template": "medication.beta.template.xml", "type": "xml", "eventData": "medications"}
  ],

  "PUBLISH": {
    "FOR_EACH_PATIENT": "patients",
    "FOR_EACH_PROVIDER": "providers",
    "FOR_EACH_ENCOUNTER": "garbage"
  }
}
